language: php
php:
 - 5.5

env:
  global:
   - secure: J5vcOHmUz7zLYSheCAZy1Q4H96MlDN4/Gci68OqvlisI0I3WilwIgOZlSKfnuu6yC6acazeRGBdrJPuUi9Us+E8IWNzBYvai+olG0A0jxhjCkWf4cjy92Bo92SZwbaOVCVnVRby1jePOrryjDngew2pWGfhFK2j8KpctmTGMk+4=

install:
 - sudo apt-get install graphviz
 - composer install --prefer-dist --dev
 - npm install -g grunt-cli
 - npm install

script:
 - grunt test

after_success:
 - grunt docs